### ISSUE TITLE
Magento 1.9.2.4

### ISSUE THREAD

**Issue by filimm** [TheExtensionLab/StatusColors#10]
Hi, Does it work with this magento version? I've installed through Magento Connect but even after cleaning the cache and logging out  and in again the extension is not showing in my admin panel.

**Comment by filimm** [comment]
Ok, I installed using modman and now it's working, Thanks!

**Comment by JamesAnelay** [comment]
Hi @filimm I saw a message saying you fixed with modman, all good now?
