### ISSUE TITLE
Is there a Magento 2 Version coming?

### ISSUE THREAD

**Issue by Drifti** [TheExtensionLab/StatusColors#11]

**Comment by JamesAnelay** [comment]
Possibly @Drifti but nothing set in stone or worked on just yet.

**Comment by stalica** [comment]
I am also interested version for Magento 2

**Comment by JamesAnelay** [comment]
Just working on the M2 version now should be available in a few days. Note there will be a small payment required for a commercial license.

**Comment by JamesAnelay** [comment]
Note i'm no longer planning to bring out an m2 version.
