### ISSUE TITLE
Doc Improvement & default Colors

### ISSUE THREAD

**Issue by winkelsdorf** [TheExtensionLab/StatusColors#2]
Hi,

great extension. But it took me a while to figure out where to set the colors and if your extension works ;)

I debugged my whole test system because I thought it was an extension conflict, missed out that the color is set in System > Order Status. Probably best to include a small screenshot for the Users where to click.

Well, beside this noob mistake I would suggest defining some "out-of-the-box" default colors so Users immediately see your extension works.

Great work!

Cheers,
Frederik

**Comment by JamesAnelay** [comment]
Hello @winkelsdorf,

We do have that in the doc http://docs.theextensionlab.com/status-colors/configuration.html but your right I need to add the doc link in the README.

RE default colours your right I did have this in a previous version and removed it for some reason.

Thanks for the feedback,
James

P.S Feel free to get involved and pull request as I will not be able to immediatly ;)

**Comment by JamesAnelay** [comment]
Just to update you @winkelsdorf, I have now added a default status colour (thanks for the suggestion). I have also made the docs link prominent in the Readme along with adding a message to the notification bar on successfull installation goes something linke "You have successfully installed TheExtensionLab_StatusColors: You can configure it at XYZ - DOC LINK"

Hopefully that should mean people have a much better installation experience.

Thanks again for the suggestions and for using the extension!

Cheers,
James

**Comment by winkelsdorf** [comment]
Glad to hear that the suggestion made it into the code and Readme :)

You're very welcome, I have to thank you!
